owner: "vmarcon"
homepage_url: "https://github.com/IFB-ElixirFr/GFLS_BIOS4BIOL"
categories:
  - "Statistics"
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }}, stastistical tool from BIOS4BIOL group, made with the help of the GFLS project."
suite:
  name: "suite_StatsExplorer_GFLS_1_0"
  description: "A suite of statistical tools designed to make simple exploratory analysis."
  long_description:
  > "Normalization : Normalize your data with some well known methods"
  > "Summary statistics : Produce simple descriptive statistics from a numerical table"
  > "Hierarchical clustering : Generate hierarchical cluster analysis on a numeric data table"
  > "PCAFactoMineR : Realize a PCA analysis using FactoMineR package"
